### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [r-okavv/exam_app#98]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
触れてみましたがREADMEに記載されている機能は問題なく動いていることを確認しました。LGTMです。

## 静的コードチェックが入っている
・インデントが崩れたり、空行があったり無かったりしていたのでRubocopの標準リントを通して修正を試みましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・一定水準の技術力を示せているかと思います。ただテーブル数が少なかったり、複雑なビジネスロジックが現状あるわけではないので、以下の高度な技術を本リリースに含められないか検討してください。

```
■レコメンド
概要：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
使用技術・ライブラリ：
- Amazon Personalize
  - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
  - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
- GCP Recommendations AI
  - https://cloud.google.com/recommendations?hl=ja
  - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
- アルゴリズム
  - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。
```

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・入力欄が黒色？になっているせいか入力した値が確認できず、不便を感じました。
・検索結果も同様に白背景の部分は分かるのですが、黒背景に入ると何が書かれているのかが分からなかったです。
・地図の表示はブラウザの横サイズに合わせて、縦サイズが変わるとPCでも見やすくなるかと感じました。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by r-okavv** [comment]
レビューありがとうございます。
レコメンド機能の追加についてissueを作成しました #99 

UIについてもアドバイスをありがとうございます。
ダークモード設定の時に入力欄が黒くなってしまうようです。
入力欄、地図の表示ついてそれぞれisuueを作成しました。 #70 #101 

本リリースは9/30を予定しています。
よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
ご回答ありがとうございます。
引き続き開発頑張ってください。
